import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#D5CDB8",
  },
  titulo: {
    alignSelf: "flex-start",
    fontSize: 45,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#3B4231",
    marginLeft: 40,
    marginBottom: 100,
    marginTop: 40,
  },
  subtitulo: {
    fontSize: 40,
    color: "#656C47",
    marginTop: 15,
  },
  avatar: {
    width: 150,
    height: 150,
    borderRadius: 75,
  },
  decisions: {
    backgroundColor: "#868D6A",
    marginTop: "auto",
    justifyContent: "flex-end",
    alignItems: "center",
    height: 143,
    width: "100%",
  },
  button: {
    backgroundColor: "#D5CDB8",
    borderRadius: 15,
    margin: 10,
    padding: 10,
    paddingHorizontal: 30,
  },
  buttonContinuar: {
    flexDirection: "row",
    backgroundColor: "#3B4231",
    borderRadius: 15,
    margin: 10,
    padding: 10,
    paddingHorizontal: 30,
  },
  buttonVoltar: {
    flexDirection: "row",
    backgroundColor: "#D5CDB8",
    borderRadius: 15,
    margin: 10,
    padding: 10,
    paddingHorizontal: 30,
  },
  decisionsContinuar: {
    color: "#FFFFFF",
  },
  decisionsVoltar: {
    color: "#3B4231",
  },
  etapasProcesso: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    width: "80%",
    height: 10,
    marginTop: 20,
  },
  etapasPreenchido: {
    backgroundColor: "#3B4231",
    borderRadius: 20,
    flex: 1,
    marginHorizontal: 3,
  },
  etapasVazio: {
    backgroundColor: "#D9D9D9D9",
    borderRadius: 20,
    flex: 1,
    marginHorizontal: 3,
  },
  inputContainers: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: -80,
    alignItems: "center",
    width: "70%",
  },
  inputContainer: {
    width: "45%",
    borderColor: "#3B4231",
    borderWidth: 1,
    borderRadius: 10,
    width: 105,
    height: 84,
  },
  inputFisico: {
    color: "#3B4231",
    fontSize: 16,
    marginBottom: 5,
    marginLeft: 10,
  },
  inputArea: {
    backgroundColor: "#D9D9D9",
    borderRadius: 10,
    padding: 10,
    color: "#3B4231",
    marginHorizontal: 10,
  },
  scrollView: {
    width: "100%",
  },
  scrollContent: {
    alignItems: "center",
    paddingBottom: 24,
    paddingHorizontal: 16,
  },
  containersSelecao: {
    backgroundColor: "#BCAD88",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "80%",
    marginTop: 20,
    borderRadius: 10,
    paddingBottom: 10,
    paddingHorizontal: 10,
  },
  containerSelecao: {
    flexDirection: "row",
    marginTop: 20,
    marginHorizontal: 10,
    justifyContent: "space-between",
    width: "80%",
  },
  opcaoSelecao: {
    backgroundColor: "#D9D9D9",
    borderRadius: 10,
    borderColor: "#3B4231",
    borderWidth: 1,
    width: "60%",
    height: 36,
    justifyContent: "center",
    alignItems: "center",
  },
  opcaoSelecionada: {
    backgroundColor: "#3B42314d",
    borderColor: "#3B4231",
  },
  textoSelecao: {
    color: "#3B4231",
    fontSize: 19,
    fontFamily: "Basic",
    fontWeight: "regular",
  },
  opcaoInput: {
    fontSize: 16,
    color: "#3B4231",
    padding: 10,
  },
  opcaoInputContainer: {
    backgroundColor: "#D9D9D9",
    borderRadius: 10,
    borderColor: "#3B4231",
    width: "100%",
    marginTop: 10,
    alignSelf: "center",
    borderWidth: 1,
  },
  summaryBox: {
    backgroundColor: "#F1E9D7",
    borderRadius: 12,
    padding: 20,
    width: "90%",
    alignSelf: "center",
    marginBottom: 20,
  },
  summaryLabel: {
    color: "#3B4231",
    fontSize: 18,
    fontWeight: "700",
  },
  summaryValue: {
    color: "#3B4231",
    fontSize: 16,
    marginTop: 8,
    lineHeight: 24,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#D9D9D9",
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3B4231",
    marginTop: 15,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#3B4231",
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  checkboxChecked: {
    backgroundColor: "#3B4231",
    borderColor: "#3B4231",
  },
  captchaText: {
    color: "#3B4231",
    fontSize: 16,
    fontWeight: "600",
  },
  buttonDisabled: {
    opacity: 0.5,
  },
});
